version: '3.8'

services:
  # API Gateway v2.0
  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SECRET=your-super-secret-jwt-key-here
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - PROXY_TIMEOUT=15000
      - LOG_LEVEL=debug
    depends_on:
      - auth-service
      - product-service
    networks:
      - microservices-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/auth_service
      - JWT_SECRET=your-super-secret-jwt-key-here
      - KAFKA_BROKER=localhost:9092
    depends_on:
      - mongodb
    networks:
      - microservices-network

  # Product Service
  product-service:
    build: ./services/product-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/product_service
      - JWT_SECRET=your-super-secret-jwt-key-here
    depends_on:
      - mongodb
    networks:
      - microservices-network
    restart: unless-stopped

  # Using existing Kafka services (external)

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

volumes:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge

